# -*- coding: utf-8 -*-
"""baseball_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPkBXMY1Y3bjBHVNds2FBpfDRF9_eEe4
"""

def calPoints(operations):
  ans = []
  for score in operations:
    try:
      number = int(score)
      if isinstance(number,int):
        ans.append(number)
    except ValueError:
      if score == "C":
        ans.pop()
      elif score == "D":
        if ans:
          double = ans[-1] * 2
          ans.append(double)
      elif score == "+":
        if len(ans) >=2:
          sum_scores = sum(ans[-2:])
          ans.append(sum_scores)

  return sum(ans)