# -*- coding: utf-8 -*-
"""concatenation of array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPkBXMY1Y3bjBHVNds2FBpfDRF9_eEe4
"""

def getConcatenation(nums):
  n = len(nums)
  ans = [0] * (2*n)

  for i in range(len(nums)):
    ans[i] = nums[i]
    ans[i+n] = nums[i]
  return ans