# -*- coding: utf-8 -*-
"""Min Stack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPkBXMY1Y3bjBHVNds2FBpfDRF9_eEe4
"""

class MinStack:

    def __init__(self):
      self.stack = []
      self.min_stack = []


    def push(self, val: int) -> None:
      self.stack.append(val)
      if not self.min_stack or val <= self.min_stack[-1]:
        self.min_stack.append(val)



    def pop(self) -> None:
      if self.stack:
        if self.stack[-1] == self.min_stack[-1]:
          self.min_stack.pop()
        self.stack.pop()



    def top(self) -> int:
      if self.stack:
        return self.stack[-1]


    def getMin(self) -> int:
      if self.min_stack:
        return self.min_stack[-1]