# -*- coding: utf-8 -*-
"""remove duplicates from sorted array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPkBXMY1Y3bjBHVNds2FBpfDRF9_eEe4
"""

def removeduplicates(nums):
  i = 1
  j = 1
  while i < len(nums):
    if nums[i] != nums[i-1]:
      nums[j] = nums[i]
      j += 1
    i += 1
  return j