# -*- coding: utf-8 -*-
"""remove Element.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPkBXMY1Y3bjBHVNds2FBpfDRF9_eEe4
"""

def removeElement(nums,val):
  i = 0
  j = 0

  while i < len(nums):

    if nums[i] != val:
      nums[j] = nums[i]
      j+=1
    i+=1
  return nums[:j]