# -*- coding: utf-8 -*-
"""valid parantheses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZn31djt89QX3h0jxJp9NI5huo9G5uYn
"""

def isValid(s):
  stack = []
  parantheses_dict = {')':'(','}':'{',']':'['}
  for char in s:
    if char in parantheses_dict.values():
      stack.append(char)
    elif char in parantheses_dict:
      if not stack or stack.pop() != parantheses_dict[char]:
        return False
    else:
      continue
  return not stack